import com.bank.drool_reward.dto.RewardStatus;
global com.bank.drool_reward.services.RewardStatusService rewardStatusService;
import com.bank.drool_reward.model.T003922Table;
import com.bank.drool_reward.model.T001906Table;
import com.bank.drool_reward.model.T000820Table;
import com.bank.drool_reward.model.T000070Table;
import java.lang.System;
import com.bank.drool_reward.util.ComponentConstantString;
import com.bank.drool_reward.util.DataConversion;
import com.bank.drool_reward.dto.RewardManage;
global com.bank.drool_reward.services.RewardManageService rewardManageService;
import java.util.Calendar;
import java.util.Date;

rule "Input Parameter Should be AlphaNumeric for RewardStatus"
  when
		$tbl22:T003922Table()
		$rewardObj : RewardStatus(DataConversion.isAlphaNumeric(getClientApplication()) &&
		DataConversion.isAlphaNumeric(getDataSourceId()) &&
		DataConversion.isAlphaNumeric(getPrimaryKey()) && requestAction.equals("ACCERN-INQ") &&
		(keyType.equals(ComponentConstantString.UID_TYPE) || keyType.equals(ComponentConstantString.EAC_TYPE)))
	then
		$tbl22.setValidRequest(true);
		


end;


rule "For EAC TO UID CONVERSION FOR STATUS"
	when
		$tbl22:T003922Table()
		$rewardObj : RewardStatus(keyType.equals(ComponentConstantString.EAC_TYPE))
	then
				
		$tbl22.setaCCT_UID(rewardStatusService.fetchUId($rewardObj.getPrimaryKey()));
end;



rule  "To SET REWARD_STATUS"
when
	$dataObj : T000820Table($dataObj != null)
		if ($dataObj.getrWAE_EXP_DTE().isEmpty()) 										do[setStatusInactive]
			 else if (! DataConversion.dateCompare($dataObj.getrWAE_EXP_DTE())) 		do[setStatusInactive2]	
				else if (DataConversion.dateCompare($dataObj.getrWAE_EXP_DTE())) 		do[setStatusActive]	
then
	 System.out.println("To SET REWARD_STATUS Rule Executed....");
	 then[setStatusInactive]
	 	$dataObj.setrWAE_STATUS(ComponentConstantString.REWARD_STATUS_ACTIVE);
			 then[setStatusInactive2]
	 	 		$dataObj.setrWAE_STATUS(ComponentConstantString.REWARD_STATUS_INACTIVE);
	 				then[setStatusActive]
	 					 $dataObj.setrWAE_STATUS(ComponentConstantString.REWARD_STATUS_ACTIVE);
end;


rule "Input Parameter Should be AlphaNumeric for RewardManage"
	when
		$tbl221:T003922Table()
		$rewardObj : RewardManage(DataConversion.isAlphaNumeric(getClientApplication()) &&
		DataConversion.isAlphaNumeric(getDataSourceId()) &&
		DataConversion.isAlphaNumeric(getBuisnessProcess()) &&
		DataConversion.isAlphaNumeric(getBuisnessSubprocess()) &&
		DataConversion.isAlphaNumeric(getPrimaryKey()) && requestAction.equals("ACCERN-UPD") &&
		(keyType.equals(ComponentConstantString.UID_TYPE) || keyType.equals(ComponentConstantString.EAC_TYPE)))
	then
		$tbl221.setValidRequest(true);
end;



rule "For EAC TO UID CONVERSION FOR REWARDMANAGE"
	when
		$tbl22:T003922Table()
		$rewardObj1 : RewardManage(keyType.equals(ComponentConstantString.EAC_TYPE))
	then
		$tbl22.setaCCT_UID(rewardManageService.fetchUId($rewardObj1.getPrimaryKey()));
		
end;

rule "CUT OF TIME FOR MANAGE"
	when
		$table:T000070Table($table != null)
			if(DataConversion.compareTimeWithCurrentTime(rewardManageService.Hrs,rewardManageService.Min) > 0) do[setExpDate1]	
				else do[setExpDate2]		
		 
	then
		System.out.println("CUT OF TIME FOR MANAGE Rule Executed............");
		
			then[setExpDate1]	
				Date currentDate = new Date();	
				Date dt = new Date();
				Calendar c = Calendar.getInstance();
				c.setTime(currentDate);
				c.add(Calendar.DATE, 1); // Date With +1 day from the current date
				dt = c.getTime();
				rewardManageService.globalStartDate = dt;
				rewardManageService.globalExpireDate = currentDate;
				
					then[setExpDate2]	
						Date currentDate = new Date();
						Date dt1 = new Date();
						Calendar c = Calendar.getInstance();
						c.setTime(currentDate);
						c.add(Calendar.DATE, -1); // Date With -1 day from the current date
						dt1 = c.getTime();
						rewardManageService.globalStartDate = currentDate;
						rewardManageService.globalExpireDate = dt1;
		 
end;


