	template header
	
	name
	object
	conditional
	action
	
	package templates;
	
	global com.bank.drool_reward.model.Transaction transaction;
	
	import java.text.SimpleDateFormat;
	import function com.bank.drool_reward.util.DroolsUtility.debug;
	
	dialect "java"
	
	template "Transaction"
	
	rule "@{row.rowNumber} - @{name}"
	when
	    @{object}(@{conditional})
	     
	then
	    transaction.setReward(@{action});
			debug(drools);
	end
	
	end template